# Generated by Django 2.2.4 on 2019-08-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='allImages/'),
        ),
    ]
