# Generated by Django 2.2.4 on 2019-08-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190831_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotpreference',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spotpreference',
            name='image',
        ),
    ]
