# Generated by Django 2.2.4 on 2019-09-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190831_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='allImages/'),
        ),
    ]
