# Generated by Django 2.2.2 on 2019-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190901_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='holiday',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
