# Generated by Django 2.2.4 on 2019-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190916_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotreview',
            name='rating',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
    ]
